const HOTEL_COLLECTION = "Hotels";
const MOSTSEARCHED_COLLECTION = "Most Searched";
const TOPREVIEWS_COLLECTION = "Discovery-Top Reviews";
const BEST_COLLECTION = "Discovery-Best";
const LOWESTPRICE_COLLECTION = "Discovery-Lowest Price";
const MOSTSTARS_COLLECTION = "Discovery-Most Stars";
const MORE_COLLECTION = "Discovery-More";

module.exports = {
  HOTEL_COLLECTION,
  MOSTSEARCHED_COLLECTION,
  TOPREVIEWS_COLLECTION,
  BEST_COLLECTION,
  LOWESTPRICE_COLLECTION,
  MOSTSTARS_COLLECTION,
  MORE_COLLECTION,
};
